status = [
  # Buildkite: impure builds
  "buildkite/offchain-metadata-tools",
  # Hydra: build for required jobset
  "ci/hydra:Cardano:offchain-metadata-tools:required",
  "ci/hydra-eval",
  "ci/hydra-build:required",
]
timeout_sec = 7200
required_approvals = 1
delete_merged_branches = true
block_labels = [ "WIP", "DO NOT MERGE", "wip" ]
