env:
  LC_ALL: "en_US.UTF-8"

steps:
  - label: 'Update docs'
    command:
      - nix-build -A maintainer-scripts.update-docs -o update-docs.sh
      - ./update-docs.sh
    agents:
      system: x86_64-linux
    branches: "master"

  - label: 'Check Stylish Haskell'
    command: 'nix-shell --run .buildkite/check-stylish.sh'
    agents:
      system: x86_64-linux
